ecommerce/demo/urls.py
from django.urls import path

from . import views

app_name = "demo"

urlpatterns = [
    path("", views.home, name="home"),
    path("categories/", views.category),
    path(
        "product-by-category/<slug:category>/",
        views.product_by_category,
        name="product_by_category",
    ),
    path("<slug:slug>", views.product_detail, name="product_detail"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from elasticsearch_dsl import Search
from rest_framework import routers

from ecommerce.drf import views
from ecommerce.drf.views import (
    CategoryList,
    ProductByCategory,
    ProductInventoryByWebId,
)
from ecommerce.search.views import SearchProductInventory

router = routers.DefaultRouter()
router.register(r"api", views.AllProductViewset, basename="allproducts")
router.register(
    r"product/(?P<slug>[^/.]+)",
    views.ProductInventoryViewset,
    basename="products",
)
router.register(
    r"category/(?P<slug>[^/.]+)",
    views.ProductByCategory,
    basename="productbycategory",
)
router.register(
    r"api/inventory/products/category/(?P<slug>[^/.]+)",
    views.ProductByCategory,
    basename="productsbycategory",
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("demo/", include("ecommerce.demo.urls", namespace="demo")),
    path("", include(router.urls)),
    path("search/<str:query>/", SearchProductInventory.as_view()),
    path("ninja/", include("ecommerce.dninja.urls")),
    path("api/inventory/category/all/", CategoryList.as_view()),
    path(
        "api/inventory/<int:query>/",
        ProductInventoryByWebId.as_view(),
    ),
]

ecommerce/demo/views.py
from django.contrib.postgres.aggregates import ArrayAgg
from django.db.models import Count
from django.shortcuts import render
from ecommerce.inventory import models


def home(request):
    return render(request, "index.html")


def category(request):

    data = models.Category.objects.all()

    return render(request, "categories.html", {"data": data})


def product_by_category(request, category):

    data = models.Product.objects.filter(category__name=category).values(
        "id",
        "name",
        "slug",
        "category__name",
        "product__store_price",
    )

    return render(request, "product_by_category.html", {"data": data})


def product_detail(request, slug):

    filter_arguments = []

    if request.GET:
        for value in request.GET.values():
            filter_arguments.append(value)

        data = (
            models.ProductInventory.objects.filter(product__slug=slug)
            .filter(attribute_values__attribute_value__in=filter_arguments)
            .annotate(num_tags=Count("attribute_values"))
            .filter(num_tags=len(filter_arguments))
            .values(
                "id",
                "sku",
                "product__name",
                "store_price",
                "product_inventory__units",
            )
            .annotate(field_a=ArrayAgg("attribute_values__attribute_value"))
            .get()
        )
    else:

        data = (
            models.ProductInventory.objects.filter(product__slug=slug)
            .filter(is_default=True)
            .values(
                "id",
                "sku",
                "product__name",
                "store_price",
                "product_inventory__units",
            )
            .annotate(field_a=ArrayAgg("attribute_values__attribute_value"))
            .get()
        )

    y = (
        models.ProductInventory.objects.filter(product__slug=slug)
        .distinct()
        .values(
            "attribute_values__product_attribute__name",
            "attribute_values__attribute_value",
        )
    )

    z = (
        models.ProductTypeAttribute.objects.filter(
            product_type__product_type__product__slug=slug
        )
        .distinct()
        .values("product_attribute__name")
    )

    return render(
        request, "product_detail.html", {"data": data, "y": y, "z": z}
    )

ecommerce/demo/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap demo</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
              crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
                crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.3.slim.js"
                integrity="sha256-DKU1CmJ8kBuEwumaLuh9Tl/6ZB6jzGOBV/5YpNE2BWc="
                crossorigin="anonymous"></script>
    </head>
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

ecommerce/demo/templates/categories.html
{% extends 'base.html' %}

{% block content %}

<h1>Categories</h1>

{% for x in data %}

    <a href="{% url 'demo:product_by_category' category=x.slug %}"> {{x.name}}</a>

{% endfor %}

{% endblock content %}

ecommerce/demo/templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Homepage</h1>
<a href="categories/"> Categories </a>

{% endblock content %}

ecommerce/demo/templates/product_by_category.html
{% extends 'base.html' %}

{% block content %}
<ul>
    {% for x in data %}
      <li class="text-capitalize">
      {{x.name}} [<a href="{% url 'demo:product_detail' slug=x.slug %}">view</a>]
      </li>
      <ul class="list-unstyled">
      <li>{{x.id}}</li>
      <li>Price: £{{x.product__store_price}}</li>
      </ul>
    {% endfor %}
  </ul>
{% endblock content %}

ecommerce/demo/templates/product_detail.html
{% extends "base.html" %}
{% block content %}
    product detail
    <ul>
        <li>{{ data.product__name }}</li>
        <li>{{ data.sku }}</li>
        <li>Price: ${{data.store_price}}</li>
        <li>{{ data.product_inventory__units }}</li>
    </ul>
    <ul>
        {% for x in z %}
            <li>
                {{ x.product_attribute__name }}
                <ul>
                    {% for a in y %}
                        {% if a.attribute_values__product_attribute__name == x.product_attribute__name %}
                            {% if a.attribute_values__attribute_value in data.field_a %}
                                <li>
                                    <div id="target-{{ a.attribute_values__attribute_value }}"
                                         class="selected fw-bold btn btn-primary"
                                         data-attribute="{{ x.product_attribute__name }}"
                                         value="{{ a.attribute_values__attribute_value }}">
                                        {{ a.attribute_values__attribute_value }}
                                    </div>
                                </li>
                            {% else %}
                                <li>
                                    <div id="target-{{ a.attribute_values__attribute_value }}"
                                         class="btn btn-link"
                                         data-attribute="{{ x.product_attribute__name }}"
                                         value="{{ a.attribute_values__attribute_value }}">
                                        {{ a.attribute_values__attribute_value }}
                                    </div>
                                </li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
    <script>
        var d = {}
    
        let textBoxes = document.querySelectorAll('[id^=target]')
        let e = 0
        let f = textBoxes.length
    
        for (let i in textBoxes) {
            if (e < f){
                if (textBoxes[i].classList.contains("selected")){
                    d[textBoxes[i].getAttribute('data-attribute')] = textBoxes[i].getAttribute('value')
                }
            } else {
                break
            }
            e++
        }
        $('[id^=target]').click(function () {
            const value = this.getAttribute('value');
            d[this.getAttribute('data-attribute')] = this.getAttribute('value')
            const querystring = buildUrlWithParams(d)
            const url = window.location.href.split('?')[0]
            window.location.href = url + "?" + querystring;
        });
        function buildUrlWithParams(data){
            var searchParams = [];
            for (var d in data){
                searchParams.push(d + '=' + data[d]);
            }
            return searchParams.join('&')
        }
    
    </script>
{% endblock content %}